/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInner;
import com.sentry.api.client.model.ResolveAnEventID200ResponseEventErrorsInner;
import com.sentry.api.client.model.ResolveAnEventID200ResponseEventUser;
import com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseMeta;
import com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseMetadata;
import com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseSdk;
import com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseTagsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListAnIssueSHashes200ResponseInnerLatestEvent
 */
public class ListAnIssueSHashes200ResponseInnerLatestEventTest {
    private final ListAnIssueSHashes200ResponseInnerLatestEvent model = new ListAnIssueSHashes200ResponseInnerLatestEvent();

    /**
     * Model tests for ListAnIssueSHashes200ResponseInnerLatestEvent
     */
    @Test
    public void testListAnIssueSHashes200ResponseInnerLatestEvent() {
        // TODO: test ListAnIssueSHashes200ResponseInnerLatestEvent
    }

    /**
     * Test the property 'eventID'
     */
    @Test
    public void eventIDTest() {
        // TODO: test eventID
    }

    /**
     * Test the property 'dist'
     */
    @Test
    public void distTest() {
        // TODO: test dist
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateReceived'
     */
    @Test
    public void dateReceivedTest() {
        // TODO: test dateReceived
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'entries'
     */
    @Test
    public void entriesTest() {
        // TODO: test entries
    }

    /**
     * Test the property 'packages'
     */
    @Test
    public void packagesTest() {
        // TODO: test packages
    }

    /**
     * Test the property 'sdk'
     */
    @Test
    public void sdkTest() {
        // TODO: test sdk
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'contexts'
     */
    @Test
    public void contextsTest() {
        // TODO: test contexts
    }

    /**
     * Test the property 'fingerprints'
     */
    @Test
    public void fingerprintsTest() {
        // TODO: test fingerprints
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'groupID'
     */
    @Test
    public void groupIDTest() {
        // TODO: test groupID
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
