/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sentry.api.client.model.ListAnIssueSHashes200ResponseInnerLatestEvent;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListAnIssueSHashes200ResponseInner
 */
public class ListAnIssueSHashes200ResponseInnerTest {
    private final ListAnIssueSHashes200ResponseInner model = new ListAnIssueSHashes200ResponseInner();

    /**
     * Model tests for ListAnIssueSHashes200ResponseInner
     */
    @Test
    public void testListAnIssueSHashes200ResponseInner() {
        // TODO: test ListAnIssueSHashes200ResponseInner
    }

    /**
     * Test the property 'latestEvent'
     */
    @Test
    public void latestEventTest() {
        // TODO: test latestEvent
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
