/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ResolveAnEventID200ResponseEventContextsOrganization
 */
public class ResolveAnEventID200ResponseEventContextsOrganizationTest {
    private final ResolveAnEventID200ResponseEventContextsOrganization model = new ResolveAnEventID200ResponseEventContextsOrganization();

    /**
     * Model tests for ResolveAnEventID200ResponseEventContextsOrganization
     */
    @Test
    public void testResolveAnEventID200ResponseEventContextsOrganization() {
        // TODO: test ResolveAnEventID200ResponseEventContextsOrganization
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

}
