/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf
 */
public class RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOfTest {
    private final RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf model = new RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf();

    /**
     * Model tests for RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf
     */
    @Test
    public void testRetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf() {
        // TODO: test RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf
    }

    /**
     * Test the property 'environment'
     */
    @Test
    public void environmentTest() {
        // TODO: test environment
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'dateStarted'
     */
    @Test
    public void dateStartedTest() {
        // TODO: test dateStarted
    }

    /**
     * Test the property 'dateFinished'
     */
    @Test
    public void dateFinishedTest() {
        // TODO: test dateFinished
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
