/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveAnIssue200ResponseStats
 */
public class RetrieveAnIssue200ResponseStatsTest {
    private final RetrieveAnIssue200ResponseStats model = new RetrieveAnIssue200ResponseStats();

    /**
     * Model tests for RetrieveAnIssue200ResponseStats
     */
    @Test
    public void testRetrieveAnIssue200ResponseStats() {
        // TODO: test RetrieveAnIssue200ResponseStats
    }

    /**
     * Test the property '_24h'
     */
    @Test
    public void _24hTest() {
        // TODO: test _24h
    }

    /**
     * Test the property '_30d'
     */
    @Test
    public void _30dTest() {
        // TODO: test _30d
    }

}
