/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveAnEventForAProject200ResponseMetadataOneOf
 */
public class RetrieveAnEventForAProject200ResponseMetadataOneOfTest {
    private final RetrieveAnEventForAProject200ResponseMetadataOneOf model = new RetrieveAnEventForAProject200ResponseMetadataOneOf();

    /**
     * Model tests for RetrieveAnEventForAProject200ResponseMetadataOneOf
     */
    @Test
    public void testRetrieveAnEventForAProject200ResponseMetadataOneOf() {
        // TODO: test RetrieveAnEventForAProject200ResponseMetadataOneOf
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
