/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.BulkMutateAListOfIssues200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.BulkMutateAListOfIssuesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.BulkMutateAListOfIssuesRequestStatusDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ConfigValidator.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateAMonitorRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateAMonitorRequestAlertRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateAMonitorRequestAlertRuleTargetsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewCheckInRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewCheckInRequestMonitorConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewClientKeyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewDeployForAnOrganizationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewProjectRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewReleaseForAnOrganizationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewReleaseForAnOrganizationRequestCommitsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewReleaseForAnOrganizationRequestCommitsInnerPatchSetInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewReleaseForAnOrganizationRequestRefsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateANewTeamRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateAnExternalIssue200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.CreateAnExternalIssueRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.DebugIssuesRelatedToSourceMapsForAGivenEvent200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.DebugIssuesRelatedToSourceMapsForAGivenEvent200ResponseErrorsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSClientKeys200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSClientKeys200ResponseInnerBrowserSdk.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSClientKeys200ResponseInnerDsn.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSEvents200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSEvents200ResponseInnerTagsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSIssues200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSIssues200ResponseInnerMetadata.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSIssues200ResponseInnerMetadataOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSIssues200ResponseInnerProject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSIssues200ResponseInnerStats.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSServiceHooks200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSUserFeedback200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSUserFeedback200ResponseInnerEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAProjectSUsers200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListARepositorySCommits200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListATagSValues200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListATagSValuesRelatedToAnIssue200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnIssueSHashes200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnIssueSHashes200ResponseInnerLatestEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSIntegrationPlatformInstallations200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSIntegrationPlatformInstallations200ResponseInnerApp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSIntegrationPlatformInstallations200ResponseInnerOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSMembers200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSMembers200ResponseResourcesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSMembers200ResponseResourcesInnerEmailsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSMembers200ResponseResourcesInnerName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSPaginatedTeams200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSPaginatedTeams200ResponseResourcesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMembersInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSPaginatedTeams200ResponseResourcesInnerMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSProjects200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSProjects200ResponseInnerEventProcessing.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSProjects200ResponseInnerLatestRelease.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSProjects200ResponseInnerTeam.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSProjects200ResponseInnerTeamsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSReleaseFiles200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSReleaseFiles200ResponseInnerHeaders.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSRepositories200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSTeams200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSTeams200ResponseInnerOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSTeams200ResponseInnerOrganizationLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSUsers200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSUsers200ResponseInnerFlags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSUsers200ResponseInnerUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListAnOrganizationSUsers200ResponseInnerUserEmailsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ListYourProjects200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.Monitor.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.MonitorAlertRuleTargetValidator.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.MonitorAlertRuleValidator.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.MonitorCheckIn.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.MonitorCheckInValidator.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.MonitorValidator.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.OrganizationEventsResponseDict.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.OrganizationMemberSCIM.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.OrganizationMemberWithRoles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.OutcomesResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.Project.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ProjectPost.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ProvisionANewOrganizationMemberRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ProvisionANewTeamRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.QueryAnIndividualTeam200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.QueryAnIndividualTeam200ResponseMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.QueryDiscoverEventsInTableFormat200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.QueryDiscoverEventsInTableFormat200ResponseMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RegisterANewServiceHookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAShortID200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAShortID200ResponseGroup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAShortID200ResponseGroupAssignedTo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAShortID200ResponseGroupMetadata.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAShortID200ResponseGroupProject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAShortID200ResponseGroupSubscriptionDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContextSession.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContexts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContextsBrowser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContextsForbiddenError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContextsForbiddenErrorResponseJSON.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContextsOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventContextsTrace.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf1Data.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf1DataEnv.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf2Data.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3Data.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3DataValuesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3DataValuesInnerMechanism.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktrace.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOf3DataValuesInnerStacktraceFramesInnerContextInnerInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOfData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOfDataValuesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventErrorsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventMetadata.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventPackages.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventTagsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.ResolveAnEventID200ResponseEventUserData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponseLatestRelease.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponseLatestReleaseAuthorsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponseLatestReleaseProjectsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponseOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponsePluginsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponsePluginsInnerAuthor.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAProject200ResponsePluginsInnerResourceLinksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveATeam200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveATeam200ResponseAvatar.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveATeam200ResponseOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseContextResp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseErrorsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseErrorsInnerData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseMetadata.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseMetadataOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseMetadataOneOf1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseRelease.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseReleaseAllOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeploy.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseReleaseAllOfLastDeployOneOf1Not.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseSdk.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseTagsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnIssue200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnIssue200ResponseActivityInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnIssue200ResponseFirstRelease.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnIssue200ResponseStats.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganization200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganization200ResponseAvailableRolesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganization200ResponseOnboardingTasksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganization200ResponseProjectsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganization200ResponseProjectsInnerTeam.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganization200ResponseQuota.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseExternalUsersInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseFlags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseGroupOrgRolesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseTeamRolesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseUserAvatar.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseUserEmailsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseUserIdentitiesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseUserIdentitiesInnerOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveAnOrganizationMember200ResponseUserIdentitiesInnerProvider.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveCheckInsForAMonitor200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveEventCountsForAnOrganizationV2200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveEventCountsForAnOrganizationV2200ResponseGroupsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveMonitorsForAnOrganization200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveMonitorsForAnOrganization200ResponseInnerProject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveReleaseHealthSessionStatistics200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveReleaseHealthSessionStatistics200ResponseGroupsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveReleaseHealthSessionStatistics200ResponseGroupsInnerBy.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveReleaseHealthSessionStatistics200ResponseGroupsInnerTotals.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveReleaseHealthSessionStatistics400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.RetrieveTagDetails200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMListResponseEnvelopeSCIMMemberIndexResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMListResponseEnvelopeSCIMTeamIndexResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMMemberProvision.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMPatchOperation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMPatchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMTeamPatchOperation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMTeamPatchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SCIMTeamRequestBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SourceMapDebug.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.SubmitUserFeedbackRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.Team.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.TeamPost.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.TeamSCIM.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAClientKeyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAProjectRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateATeam200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateATeamRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateATeamSAttributesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateATeamSAttributesRequestOperationsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnIssue200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnIssueRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnOrganizationMemberSAttributesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnOrganizationMemberSAttributesRequestOperationsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnOrganizationReleaseFileRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnOrganizationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.sentry.api.client.model.UpdateAnOrganizationSReleaseRequest.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
