/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateANewCheckInRequestMonitorConfig
 */
public class CreateANewCheckInRequestMonitorConfigTest {
    private final CreateANewCheckInRequestMonitorConfig model = new CreateANewCheckInRequestMonitorConfig();

    /**
     * Model tests for CreateANewCheckInRequestMonitorConfig
     */
    @Test
    public void testCreateANewCheckInRequestMonitorConfig() {
        // TODO: test CreateANewCheckInRequestMonitorConfig
    }

    /**
     * Test the property 'scheduleType'
     */
    @Test
    public void scheduleTypeTest() {
        // TODO: test scheduleType
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'checkinMargin'
     */
    @Test
    public void checkinMarginTest() {
        // TODO: test checkinMargin
    }

    /**
     * Test the property 'maxRuntime'
     */
    @Test
    public void maxRuntimeTest() {
        // TODO: test maxRuntime
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

}
