/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ResolveAnEventID200ResponseEventEntriesInnerAnyOfDataValuesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ResolveAnEventID200ResponseEventEntriesInnerAnyOfData
 */
public class ResolveAnEventID200ResponseEventEntriesInnerAnyOfDataTest {
    private final ResolveAnEventID200ResponseEventEntriesInnerAnyOfData model = new ResolveAnEventID200ResponseEventEntriesInnerAnyOfData();

    /**
     * Model tests for ResolveAnEventID200ResponseEventEntriesInnerAnyOfData
     */
    @Test
    public void testResolveAnEventID200ResponseEventEntriesInnerAnyOfData() {
        // TODO: test ResolveAnEventID200ResponseEventEntriesInnerAnyOfData
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
