/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateAProjectRequest
 */
public class UpdateAProjectRequestTest {
    private final UpdateAProjectRequest model = new UpdateAProjectRequest();

    /**
     * Model tests for UpdateAProjectRequest
     */
    @Test
    public void testUpdateAProjectRequest() {
        // TODO: test UpdateAProjectRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'isBookmarked'
     */
    @Test
    public void isBookmarkedTest() {
        // TODO: test isBookmarked
    }

    /**
     * Test the property 'digestsMinDelay'
     */
    @Test
    public void digestsMinDelayTest() {
        // TODO: test digestsMinDelay
    }

    /**
     * Test the property 'digestsMaxDelay'
     */
    @Test
    public void digestsMaxDelayTest() {
        // TODO: test digestsMaxDelay
    }

}
