/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.sentry.api.client.JSON;

/**
 * CreateANewDeployForAnOrganizationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-16T12:40:29.777755Z[Etc/UTC]")
public class CreateANewDeployForAnOrganizationRequest {
  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private String environment;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PROJECTS = "projects";
  @SerializedName(SERIALIZED_NAME_PROJECTS)
  private List<String> projects;

  public static final String SERIALIZED_NAME_DATE_STARTED = "dateStarted";
  @SerializedName(SERIALIZED_NAME_DATE_STARTED)
  private OffsetDateTime dateStarted;

  public static final String SERIALIZED_NAME_DATE_FINISHED = "dateFinished";
  @SerializedName(SERIALIZED_NAME_DATE_FINISHED)
  private OffsetDateTime dateFinished;

  public CreateANewDeployForAnOrganizationRequest() {
  }

  public CreateANewDeployForAnOrganizationRequest environment(String environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * The environment you&#39;re deploying to.
   * @return environment
  **/
  @javax.annotation.Nonnull
  public String getEnvironment() {
    return environment;
  }


  public void setEnvironment(String environment) {
    this.environment = environment;
  }


  public CreateANewDeployForAnOrganizationRequest url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The optional URL that points to the deploy.
   * @return url
  **/
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public CreateANewDeployForAnOrganizationRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The optional name of the deploy.
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CreateANewDeployForAnOrganizationRequest projects(List<String> projects) {
    
    this.projects = projects;
    return this;
  }

  public CreateANewDeployForAnOrganizationRequest addProjectsItem(String projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * The optional list of projects to deploy.
   * @return projects
  **/
  @javax.annotation.Nullable
  public List<String> getProjects() {
    return projects;
  }


  public void setProjects(List<String> projects) {
    this.projects = projects;
  }


  public CreateANewDeployForAnOrganizationRequest dateStarted(OffsetDateTime dateStarted) {
    
    this.dateStarted = dateStarted;
    return this;
  }

   /**
   * An optional date that indicates when the deploy started.
   * @return dateStarted
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getDateStarted() {
    return dateStarted;
  }


  public void setDateStarted(OffsetDateTime dateStarted) {
    this.dateStarted = dateStarted;
  }


  public CreateANewDeployForAnOrganizationRequest dateFinished(OffsetDateTime dateFinished) {
    
    this.dateFinished = dateFinished;
    return this;
  }

   /**
   * An optional date that indicates when the deploy ended. If not provided, the current time is used.
   * @return dateFinished
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getDateFinished() {
    return dateFinished;
  }


  public void setDateFinished(OffsetDateTime dateFinished) {
    this.dateFinished = dateFinished;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateANewDeployForAnOrganizationRequest createANewDeployForAnOrganizationRequest = (CreateANewDeployForAnOrganizationRequest) o;
    return Objects.equals(this.environment, createANewDeployForAnOrganizationRequest.environment) &&
        Objects.equals(this.url, createANewDeployForAnOrganizationRequest.url) &&
        Objects.equals(this.name, createANewDeployForAnOrganizationRequest.name) &&
        Objects.equals(this.projects, createANewDeployForAnOrganizationRequest.projects) &&
        Objects.equals(this.dateStarted, createANewDeployForAnOrganizationRequest.dateStarted) &&
        Objects.equals(this.dateFinished, createANewDeployForAnOrganizationRequest.dateFinished);
  }

  @Override
  public int hashCode() {
    return Objects.hash(environment, url, name, projects, dateStarted, dateFinished);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateANewDeployForAnOrganizationRequest {\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    dateStarted: ").append(toIndentedString(dateStarted)).append("\n");
    sb.append("    dateFinished: ").append(toIndentedString(dateFinished)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("environment");
    openapiFields.add("url");
    openapiFields.add("name");
    openapiFields.add("projects");
    openapiFields.add("dateStarted");
    openapiFields.add("dateFinished");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("environment");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateANewDeployForAnOrganizationRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateANewDeployForAnOrganizationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateANewDeployForAnOrganizationRequest is not found in the empty JSON string", CreateANewDeployForAnOrganizationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CreateANewDeployForAnOrganizationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateANewDeployForAnOrganizationRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateANewDeployForAnOrganizationRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("environment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `environment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("environment").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("projects") != null && !jsonObj.get("projects").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `projects` to be an array in the JSON string but got `%s`", jsonObj.get("projects").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateANewDeployForAnOrganizationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateANewDeployForAnOrganizationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateANewDeployForAnOrganizationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateANewDeployForAnOrganizationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateANewDeployForAnOrganizationRequest>() {
           @Override
           public void write(JsonWriter out, CreateANewDeployForAnOrganizationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateANewDeployForAnOrganizationRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateANewDeployForAnOrganizationRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateANewDeployForAnOrganizationRequest
  * @throws IOException if the JSON string is invalid with respect to CreateANewDeployForAnOrganizationRequest
  */
  public static CreateANewDeployForAnOrganizationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateANewDeployForAnOrganizationRequest.class);
  }

 /**
  * Convert an instance of CreateANewDeployForAnOrganizationRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

