/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.sentry.api.client.JSON;


/**
 * RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments
 */
@JsonPropertyOrder({
  RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments.JSON_PROPERTY_NAME,
  RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments.JSON_PROPERTY_STATUS,
  RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments.JSON_PROPERTY_DATE_CREATED,
  RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments.JSON_PROPERTY_LAST_CHECK_IN,
  RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments.JSON_PROPERTY_NEXT_CHECK_IN
})
@JsonTypeName("Retrieve_monitors_for_an_organization_200_response_inner_environments")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-16T14:23:11.909078Z[Etc/UTC]")
public class RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_DATE_CREATED = "dateCreated";
  private OffsetDateTime dateCreated;

  public static final String JSON_PROPERTY_LAST_CHECK_IN = "lastCheckIn";
  private OffsetDateTime lastCheckIn;

  public static final String JSON_PROPERTY_NEXT_CHECK_IN = "nextCheckIn";
  private OffsetDateTime nextCheckIn;

  public RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments() { 
  }

  public RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments dateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATE_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }


  @JsonProperty(JSON_PROPERTY_DATE_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments lastCheckIn(OffsetDateTime lastCheckIn) {
    this.lastCheckIn = lastCheckIn;
    return this;
  }

   /**
   * Get lastCheckIn
   * @return lastCheckIn
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_CHECK_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastCheckIn() {
    return lastCheckIn;
  }


  @JsonProperty(JSON_PROPERTY_LAST_CHECK_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastCheckIn(OffsetDateTime lastCheckIn) {
    this.lastCheckIn = lastCheckIn;
  }


  public RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments nextCheckIn(OffsetDateTime nextCheckIn) {
    this.nextCheckIn = nextCheckIn;
    return this;
  }

   /**
   * Get nextCheckIn
   * @return nextCheckIn
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NEXT_CHECK_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getNextCheckIn() {
    return nextCheckIn;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_CHECK_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNextCheckIn(OffsetDateTime nextCheckIn) {
    this.nextCheckIn = nextCheckIn;
  }


  /**
   * Return true if this Retrieve_monitors_for_an_organization_200_response_inner_environments object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments retrieveMonitorsForAnOrganization200ResponseInnerEnvironments = (RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments) o;
    return Objects.equals(this.name, retrieveMonitorsForAnOrganization200ResponseInnerEnvironments.name) &&
        Objects.equals(this.status, retrieveMonitorsForAnOrganization200ResponseInnerEnvironments.status) &&
        Objects.equals(this.dateCreated, retrieveMonitorsForAnOrganization200ResponseInnerEnvironments.dateCreated) &&
        Objects.equals(this.lastCheckIn, retrieveMonitorsForAnOrganization200ResponseInnerEnvironments.lastCheckIn) &&
        Objects.equals(this.nextCheckIn, retrieveMonitorsForAnOrganization200ResponseInnerEnvironments.nextCheckIn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, dateCreated, lastCheckIn, nextCheckIn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveMonitorsForAnOrganization200ResponseInnerEnvironments {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    lastCheckIn: ").append(toIndentedString(lastCheckIn)).append("\n");
    sb.append("    nextCheckIn: ").append(toIndentedString(nextCheckIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

