/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sentry.api.client.model.RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.io.Serializable;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import com.sentry.api.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-15T10:01:41.950429Z[Etc/UTC]")
public class RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy extends AbstractOpenApiSchema, Serializable {
    private static final Logger log = Logger.getLogger(RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Object> adapterObject = gson.getDelegateAdapter(this, TypeToken.get(Object.class));
            final TypeAdapter<RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf> adapterRetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf = gson.getDelegateAdapter(this, TypeToken.get(RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf.class));

            return (TypeAdapter<T>) new TypeAdapter<RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy>() {
                @Override
                public void write(JsonWriter out, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `Object`
                    if (value.getActualInstance() instanceof Object) {
                        JsonObject obj = adapterObject.toJsonTree((Object)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf`
                    if (value.getActualInstance() instanceof RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf) {
                        JsonObject obj = adapterRetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf.toJsonTree((RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: Object, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf");
                }

                @Override
                public RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize Object
                    try {
                        // validate the JSON object to see if any exception is thrown
                        Object.validateJsonObject(jsonObject);
                        actualAdapter = adapterObject;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'Object'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for Object failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'Object'", e);
                    }

                    // deserialize RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf.validateJsonObject(jsonObject);
                        actualAdapter = adapterRetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf'", e);
                    }

                    if (match == 1) {
                        RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy ret = new RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy() {
        super("oneOf", Boolean.TRUE);
    }

    public RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy(Object o) {
        super("oneOf", Boolean.TRUE);
        setActualInstance(o);
    }

    public RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy(RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf o) {
        super("oneOf", Boolean.TRUE);
        setActualInstance(o);
    }

    static {
        schemas.put("Object", new GenericType<Object>() {
        });
        schemas.put("RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf", new GenericType<RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Object, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance == null) {
           super.setActualInstance(instance);
           return;
        }

        if (instance instanceof Object) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Object, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * Object, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf
     *
     * @return The actual instance (Object, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Object`. If the actual instance is not `Object`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Object`
     * @throws ClassCastException if the instance is not `Object`
     */
    public Object getObject() throws ClassCastException {
        return (Object)super.getActualInstance();
    }

    /**
     * Get the actual instance of `RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf`. If the actual instance is not `RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf`
     * @throws ClassCastException if the instance is not `RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf`
     */
    public RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf getRetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf() throws ClassCastException {
        return (RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with Object
    try {
      Object.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for Object failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf
    try {
      RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy with oneOf schemas: Object, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeployOneOf. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy
  * @throws IOException if the JSON string is invalid with respect to RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy
  */
  public static RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy.class);
  }

 /**
  * Convert an instance of RetrieveAnEventForAProject200ResponseReleaseOneOfLastDeploy to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

