/*
 * API Reference
 * Sentry Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: partners@sentry.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sentry.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.sentry.api.client.JSON;

/**
 * RetrieveAnOrganization200ResponseQuota
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-16T12:28:08.282703Z[Etc/UTC]")
public class RetrieveAnOrganization200ResponseQuota {
  public static final String SERIALIZED_NAME_ACCOUNT_LIMIT = "accountLimit";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_LIMIT)
  private Long accountLimit;

  public static final String SERIALIZED_NAME_MAX_RATE = "maxRate";
  @SerializedName(SERIALIZED_NAME_MAX_RATE)
  private Long maxRate;

  public static final String SERIALIZED_NAME_MAX_RATE_INTERVAL = "maxRateInterval";
  @SerializedName(SERIALIZED_NAME_MAX_RATE_INTERVAL)
  private Long maxRateInterval;

  public static final String SERIALIZED_NAME_PROJECT_LIMIT = "projectLimit";
  @SerializedName(SERIALIZED_NAME_PROJECT_LIMIT)
  private Long projectLimit;

  public RetrieveAnOrganization200ResponseQuota() {
  }

  public RetrieveAnOrganization200ResponseQuota accountLimit(Long accountLimit) {
    
    this.accountLimit = accountLimit;
    return this;
  }

   /**
   * Get accountLimit
   * @return accountLimit
  **/
  @javax.annotation.Nullable
  public Long getAccountLimit() {
    return accountLimit;
  }


  public void setAccountLimit(Long accountLimit) {
    this.accountLimit = accountLimit;
  }


  public RetrieveAnOrganization200ResponseQuota maxRate(Long maxRate) {
    
    this.maxRate = maxRate;
    return this;
  }

   /**
   * Get maxRate
   * @return maxRate
  **/
  @javax.annotation.Nullable
  public Long getMaxRate() {
    return maxRate;
  }


  public void setMaxRate(Long maxRate) {
    this.maxRate = maxRate;
  }


  public RetrieveAnOrganization200ResponseQuota maxRateInterval(Long maxRateInterval) {
    
    this.maxRateInterval = maxRateInterval;
    return this;
  }

   /**
   * Get maxRateInterval
   * @return maxRateInterval
  **/
  @javax.annotation.Nullable
  public Long getMaxRateInterval() {
    return maxRateInterval;
  }


  public void setMaxRateInterval(Long maxRateInterval) {
    this.maxRateInterval = maxRateInterval;
  }


  public RetrieveAnOrganization200ResponseQuota projectLimit(Long projectLimit) {
    
    this.projectLimit = projectLimit;
    return this;
  }

   /**
   * Get projectLimit
   * @return projectLimit
  **/
  @javax.annotation.Nullable
  public Long getProjectLimit() {
    return projectLimit;
  }


  public void setProjectLimit(Long projectLimit) {
    this.projectLimit = projectLimit;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveAnOrganization200ResponseQuota retrieveAnOrganization200ResponseQuota = (RetrieveAnOrganization200ResponseQuota) o;
    return Objects.equals(this.accountLimit, retrieveAnOrganization200ResponseQuota.accountLimit) &&
        Objects.equals(this.maxRate, retrieveAnOrganization200ResponseQuota.maxRate) &&
        Objects.equals(this.maxRateInterval, retrieveAnOrganization200ResponseQuota.maxRateInterval) &&
        Objects.equals(this.projectLimit, retrieveAnOrganization200ResponseQuota.projectLimit);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountLimit, maxRate, maxRateInterval, projectLimit);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveAnOrganization200ResponseQuota {\n");
    sb.append("    accountLimit: ").append(toIndentedString(accountLimit)).append("\n");
    sb.append("    maxRate: ").append(toIndentedString(maxRate)).append("\n");
    sb.append("    maxRateInterval: ").append(toIndentedString(maxRateInterval)).append("\n");
    sb.append("    projectLimit: ").append(toIndentedString(projectLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accountLimit");
    openapiFields.add("maxRate");
    openapiFields.add("maxRateInterval");
    openapiFields.add("projectLimit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RetrieveAnOrganization200ResponseQuota
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RetrieveAnOrganization200ResponseQuota.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RetrieveAnOrganization200ResponseQuota is not found in the empty JSON string", RetrieveAnOrganization200ResponseQuota.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!RetrieveAnOrganization200ResponseQuota.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RetrieveAnOrganization200ResponseQuota` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RetrieveAnOrganization200ResponseQuota.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RetrieveAnOrganization200ResponseQuota' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RetrieveAnOrganization200ResponseQuota> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RetrieveAnOrganization200ResponseQuota.class));

       return (TypeAdapter<T>) new TypeAdapter<RetrieveAnOrganization200ResponseQuota>() {
           @Override
           public void write(JsonWriter out, RetrieveAnOrganization200ResponseQuota value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RetrieveAnOrganization200ResponseQuota read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RetrieveAnOrganization200ResponseQuota given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RetrieveAnOrganization200ResponseQuota
  * @throws IOException if the JSON string is invalid with respect to RetrieveAnOrganization200ResponseQuota
  */
  public static RetrieveAnOrganization200ResponseQuota fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RetrieveAnOrganization200ResponseQuota.class);
  }

 /**
  * Convert an instance of RetrieveAnOrganization200ResponseQuota to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

