openapi: 3.0.3
info:
  contact:
    email: partners@sentry.io
  description: Sentry Public API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://sentry.io/terms/
  title: API Reference
  version: v0
servers:
- url: https://sentry.io/
tags:
- description: Endpoints for teams
  name: Teams
  x-display-description: false
- description: Endpoints for organizations
  name: Organizations
  x-display-description: false
- description: Endpoints for projects
  name: Projects
  x-display-description: false
- description: Endpoints for events and issues
  name: Events
  x-sidebar-name: Events & Issues
  x-display-description: false
- description: Endpoints for releases
  name: Releases
  x-display-description: false
- description: Endpoints for the integration platform
  name: Integration
  x-sidebar-name: Integration Platform
  x-display-description: false
- description: |-
    System for Cross-Domain Identity Management ([SCIM](http://www.simplecloud.info/)) is a standard implemented by Identity Providers and applications in order to facilitate federated identity management. Through these APIs you can add and delete members as well as teams. Sentry SaaS customers must be on a Business Plan with SAML2 Enabled. SCIM uses a bearer token for authentication that is created when SCIM is enabled. For how to enable SCIM, see our docs [here](/product/accounts/sso/#scim-pro[...]
     Sentry's SCIM API does not currently support syncing passwords, or setting any User attributes other than `active`.
  name: SCIM
  x-sidebar-name: SCIM (Beta)
  x-display-description: true
- description: Discover and Performance allow you to slice and dice your Error and
    Transaction events
  name: Discover
  x-sidebar-name: Discover & Performance
  x-display-description: true
- description: Endpoints for Crons
  name: Crons
  x-sidebar-name: Crons (Beta)
  x-display-description: true
paths:
  /api/0/organization/{organization_slug}/monitors/{monitor_slug}/checkins/:
    get:
      description: Retrieve a list of check-ins for a monitor
      operationId: Retrieve check-ins for a monitor
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Crons
      x-accepts: application/json
    post:
      description: |-
        Creates a new check-in for a monitor.

        If `status` is not present, it will be assumed that the check-in is starting, and be marked as `in_progress`.

        To achieve a ping-like behavior, you can simply define `status` and optionally `duration` and
        this check-in will be automatically marked as finished.

        Note: If a DSN is utilized for authentication, the response will be limited in details.
      operationId: Create a new check-in
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Crons
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organization/{organization_slug}/monitors/{monitor_slug}/checkins/{checkin_id}/:
    put:
      description: |-
        Updates a check-in.

        Once a check-in is finished (indicated via an `ok` or `error` status) it can no longer be changed.

        If you simply wish to update that the task is still running, you can simply send an empty payload.

        You may use `latest` for the `checkin_id` parameter in order to retrieve
        the most recent (by creation date) check-in which is still mutable (not marked as finished).
      operationId: Update a check-in
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Crons
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/events/:
    get:
      description: |-
        Retrieves discover (also known as events) data for a given organization.

        **Eventsv2 Deprecation Note**: Users who may be using the `eventsv2` endpoint should update their requests to the `events` endpoint outline in this document.
        The `eventsv2` endpoint is not a public endpoint and has no guaranteed availability. If you are not making any API calls to `eventsv2`, you can safely ignore this.
        Changes between `eventsv2` and `events` include:
        - Field keys in the response now match the keys in the requested `field` param exactly.
        - The `meta` object in the response now shows types in the nested `field` object.

        Aside from the url change, there are no changes to the request payload itself.

        **Note**: This endpoint is intended to get a table of results, and is not for doing a full export of data sent to
        Sentry.

        The `field` query parameter determines what fields will be selected in the `data` and `meta` keys of the endpoint response.
        - The `data` key contains a list of results row by row that match the `query` made
        - The `meta` key contains information about the response, including the unit or type of the fields requested
      operationId: Query Discover Events in Table Format
      security:
      - auth_token:
        - org:admin
        - org:read
        - org:write
      tags:
      - Discover
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/members/{member_id}/:
    delete:
      description: Remove an organization member.
      operationId: Delete an Organization Member
      security:
      - auth_token:
        - member:admin
        - member:read
        - member:write
      tags:
      - Organizations
      x-accepts: application/json
    get:
      description: |-
        Retrieve an organization member's details.

        Will return a pending invite as long as it's already approved.
      operationId: Retrieve an Organization Member
      security:
      - auth_token:
        - member:admin
        - member:read
        - member:write
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/monitors/:
    get:
      description: "Lists monitors, including nested monitor enviroments. May be filtered\
        \ to a project or environment."
      operationId: Retrieve monitors for an organization
      security:
      - auth_token:
        - org:admin
        - org:read
        - org:write
      tags:
      - Crons
      x-accepts: application/json
    post:
      description: Create a new monitor.
      operationId: Create a monitor
      security:
      - auth_token:
        - org:admin
        - org:read
        - org:write
      tags:
      - Crons
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/monitors/{monitor_slug}/:
    delete:
      description: Delete a monitor or monitor environments.
      operationId: Delete a monitor or monitor environments
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Crons
      x-accepts: application/json
    get:
      description: Retrieves details for a monitor.
      operationId: Retrieve a monitor
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Crons
      x-accepts: application/json
    put:
      description: Update a monitor.
      operationId: Update a monitor
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Crons
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/projects/:
    get:
      description: Return a list of projects bound to a organization.
      operationId: List an Organization's Projects
      security:
      - auth_token:
        - org:admin
        - org:read
        - org:write
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/scim/v2/Groups:
    get:
      description: |-
        Returns a paginated list of teams bound to a organization with a SCIM Groups GET Request.
        - Note that the members field will only contain up to 10000 members.
      operationId: List an Organization's Paginated Teams
      security:
      - auth_token:
        - team:read
      tags:
      - SCIM
      x-accepts: application/json
    post:
      description: Create a new team bound to an organization via a SCIM Groups POST
        Request. Note that teams are always created with an empty member set. The
        endpoint will also do a normalization of uppercase / spaces to lowercase and
        dashes.
      operationId: Provision a New Team
      security:
      - auth_token:
        - team:write
      tags:
      - SCIM
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/scim/v2/Groups/{team_id}:
    delete:
      description: Delete a team with a SCIM Group DELETE Request.
      operationId: Delete an Individual Team
      security:
      - auth_token:
        - team:admin
      tags:
      - SCIM
      x-accepts: application/json
    get:
      description: |-
        Query an individual team with a SCIM Group GET Request.
        - Note that the members field will only contain up to 10000 members.
      operationId: Query an Individual Team
      security:
      - auth_token:
        - team:admin
        - team:read
        - team:write
      tags:
      - SCIM
      x-accepts: application/json
    patch:
      description: |-
        Update a team's attributes with a SCIM Group PATCH Request. Valid operations are:

        * Renaming a team:
        ```json
        {
            "Operations": [{
                "op": "replace",
                "value": {
                    "id": 23,
                    "displayName": "newName"
                }
            }]
        }
        ```
        * Adding a member to a team:
        ```json
        {
            "Operations": [{
                "op": "add",
                "path": "members",
                "value": [
                    {
                        "value": 23,
                        "display": "testexample@example.com"
                    }
                ]
            }]
        }
        ```
        * Removing a member from a team:
        ```json
        {
            "Operations": [{
                "op": "remove",
                "path": "members[value eq "23"]"
            }]
        }
        ```
        * Replacing an entire member set of a team:
        ```json
        {
            "Operations": [{
                "op": "replace",
                "path": "members",
                "value": [
                    {
                        "value": 23,
                        "display": "testexample2@sentry.io"
                    },
                    {
                        "value": 24,
                        "display": "testexample3@sentry.io"
                    }
                ]
            }]
        }
        ```
      operationId: Update a Team's Attributes
      security:
      - auth_token:
        - team:admin
        - team:write
      tags:
      - SCIM
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/scim/v2/Users:
    get:
      description: Returns a paginated list of members bound to a organization with
        a SCIM Users GET Request.
      operationId: List an Organization's Members
      security:
      - auth_token:
        - member:admin
        - member:read
        - member:write
      tags:
      - SCIM
      x-accepts: application/json
    post:
      description: |-
        Create a new Organization Member via a SCIM Users POST Request.
        - `userName` should be set to the SAML field used for email, and active should be set to `true`.
        - `sentryOrgRole` can only be `admin`, `manager`, `billing`, or `member`.
        - Sentry's SCIM API doesn't currently support setting users to inactive,
        and the member will be deleted if active is set to `false`.
        - The API also does not support setting secondary emails.
      operationId: Provision a New Organization Member
      security:
      - auth_token:
        - member:admin
        - member:write
      tags:
      - SCIM
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/scim/v2/Users/{member_id}:
    delete:
      description: Delete an organization member with a SCIM User DELETE Request.
      operationId: Delete an Organization Member via SCIM
      security:
      - auth_token:
        - member:admin
      tags:
      - SCIM
      x-accepts: application/json
    get:
      description: |-
        Query an individual organization member with a SCIM User GET Request.
        - The `name` object will contain fields `firstName` and `lastName` with the values of `N/A`.
        Sentry's SCIM API does not currently support these fields but returns them for compatibility purposes.
      operationId: Query an Individual Organization Member
      security:
      - auth_token:
        - member:admin
        - member:read
        - member:write
      tags:
      - SCIM
      x-accepts: application/json
    patch:
      description: |-
        Update an organization member's attributes with a SCIM PATCH Request.
        The only supported attribute is `active`. After setting `active` to false
        Sentry will permanently delete the Organization Member.
      operationId: Update an Organization Member's Attributes
      security:
      - auth_token:
        - member:admin
        - member:write
      tags:
      - SCIM
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/stats_v2/:
    get:
      description: |-
        Query event counts for your Organization.
        Select a field, define a date range, and group or filter by columns.
      operationId: Retrieve Event Counts for an Organization (v2)
      security:
      - auth_token:
        - org:admin
        - org:read
        - org:write
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/teams/:
    get:
      description: Returns a list of teams bound to a organization.
      operationId: List an Organization's Teams
      security:
      - auth_token:
        - org:admin
        - org:read
        - org:write
      tags:
      - Teams
      x-accepts: application/json
    post:
      description: Create a new team bound to an organization.
      operationId: Create a New Team
      security:
      - auth_token:
        - org:admin
        - org:write
        - team:write
      tags:
      - Teams
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/events/{event_id}/source-map-debug/:
    get:
      description: |-
        Retrieve information about source maps for a given event.
        ```````````````````````````````````````````
        Return a list of source map errors for a given event.
      operationId: Debug issues related to source maps for a given event
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Events
      x-accepts: application/json
  /api/0/teams/{organization_slug}/{team_slug}/projects/:
    get:
      description: Return a list of projects bound to a team.
      operationId: List a Team's Projects
      security:
      - auth_token:
        - project:admin
        - project:read
        - project:write
      tags:
      - Teams
      x-accepts: application/json
    post:
      description: Create a new project bound to a team.
      operationId: Create a New Project
      security:
      - auth_token:
        - project:admin
        - project:write
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/teams/{organization_slug}/{team_slug}/:
    delete:
      description: |-
        Schedules a team for deletion.

        Note: Deletion happens asynchronously and therefore is not immediate. However once deletion has begun the state of a project changes and will be hidden from most public views.
      operationId: Delete a Team
      security:
      - auth_token:
        - team:admin
      tags:
      - Teams
      x-accepts: application/json
    get:
      description: Return details on an individual team.
      operationId: Retrieve a Team
      security:
      - auth_token:
        - team:read
      tags:
      - Teams
      x-accepts: application/json
    put:
      description: Update various attributes and configurable settings for the given
        team.
      operationId: Update a Team
      security:
      - auth_token:
        - team:write
      tags:
      - Teams
      x-content-type: application/json
      x-accepts: application/json
  /api/0/teams/{organization_slug}/{team_slug}/stats/:
    get:
      description: |-
        Return a set of points representing a normalized timestamp and the number of events seen in the period.

        Query ranges are limited to Sentry’s configured time-series resolutions.
      operationId: Retrieve Event Counts for a Team
      security:
      - auth_token:
        - team:read
      summary: "Caution: this endpoint may change in the future without notice."
      tags:
      - Teams
      x-accepts: application/json
  /api/0/organizations/:
    get:
      description: Return a list of organizations available to the authenticated session.  This
        is particularly useful for requests with an user bound context.  For API key
        based requests this will only return the organization that belongs to the
        key.
      operationId: List Your Organizations
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/eventids/{event_id}/:
    get:
      description: This resolves an event ID to the project slug and internal issue
        ID and internal event ID.
      operationId: Resolve an Event ID
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/:
    get:
      description: "Return details on an individual organization including various\
        \ details such as membership access, features, and teams."
      operationId: Retrieve an Organization
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
    put:
      description: Update various attributes and configurable settings for the given
        organization.
      operationId: Update an Organization
      security:
      - auth_token:
        - org:write
      tags:
      - Organizations
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/repos/:
    get:
      description: Return a list of version control repositories for a given organization.
      operationId: List an Organization's Repositories
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/repos/{repo_id}/commits/:
    get:
      description: Return a list of commits for a given repository.
      operationId: List a Repository's Commits
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/stats/:
    get:
      deprecated: true
      description: "This endpoint is deprecated in favor of [Organization Stats V2](/api/organizations/retrieve-event-counts-for-an-organization-v2/)."
      operationId: Retrieve Event Counts for an Organization
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/sessions/:
    get:
      description: |-
        Returns a time series of release health session statistics for projects bound to an organization.

        The interval and date range are subject to certain restrictions and rounding rules.

        The date range is rounded to align with the interval, and is rounded to at least one hour. The interval can at most be one day and at least one hour currently. It has to cleanly divide one day, for rounding reasons.

        Apart from the query parameters listed below, this endpoint also supports the usual [pagination parameters](https://docs.sentry.io/api/pagination/).
      operationId: Retrieve Release Health Session Statistics
      security:
      - auth_token:
        - "org: read"
      tags:
      - Releases
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/users/:
    get:
      description: Return a list of users that belong to a given organization.
      operationId: List an Organization's Users
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/shortids/{short_id}/:
    get:
      description: This resolves a short ID to the project slug and internal issue
        ID.
      operationId: Resolve a Short ID
      security:
      - auth_token:
        - "org: read"
      tags:
      - Organizations
      x-accepts: application/json
  /api/0/projects/:
    get:
      description: Return a list of projects available to the authenticated session.
      operationId: List Your Projects
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/:
    delete:
      description: |-
        Schedules a project for deletion.

        Deletion happens asynchronously and therefore is not immediate.
        However once deletion has begun the state of a project changes and
        will be hidden from most public views.
      operationId: Delete a Project
      security:
      - auth_token:
        - project:admin
      tags:
      - Projects
      x-accepts: application/json
    get:
      description: Return details on an individual project.
      operationId: Retrieve a Project
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
    put:
      description: Update various attributes and configurable settings for the given
        project.  Only supplied values are updated.
      operationId: Update a Project
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/files/dsyms/:
    delete:
      description: Delete a debug information file for a given project.
      operationId: Delete a Specific Project's Debug Information File
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-accepts: application/json
    get:
      description: Retrieve a list of debug information files for a given project.
      operationId: List a Project's Debug Information Files
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
    post:
      description: |-
        Upload a new debug information file for the given release.

        Unlike other API requests, files must be uploaded using the
        traditional multipart/form-data content-type.

        The file uploaded is a zip archive of an Apple .dSYM folder which
        contains the individual debug images.  Uploading through this endpoint
        will create different files for the contained images.
      operationId: Upload a New File
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-content-type: multipart/form-data
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/users/:
    get:
      description: Return a list of users seen within this project.
      operationId: List a Project's Users
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/tags/{key}/values/:
    get:
      description: "Return a list of values associated with this key.  The `query`\n\
        parameter can be used to to perform a \"contains\" match on\nvalues. \n\n\
        When [paginated](/api/pagination) can return at most 1000 values."
      operationId: List a Tag's Values
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/stats/:
    get:
      description: |-
        Return a set of points representing a normalized timestamp and the
        number of events seen in the period.

        Query ranges are limited to Sentry's configured time-series resolutions.
      operationId: Retrieve Event Counts for a Project
      security:
      - auth_token:
        - project:read
      summary: |-
        Caution
        This endpoint may change in the future without  notice.
      tags:
      - Projects
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/user-feedback/:
    get:
      description: Return a list of user feedback items within this project.
      operationId: List a Project's User Feedback
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
    post:
      description: |-
        Submit and associate user feedback with an issue.

        Feedback must be received by the server no more than 30 minutes after the event was saved.

        Additionally, within 5 minutes of submitting feedback it may also be overwritten. This is useful in situations where you may need to retry sending a request due to network failures.

        If feedback is rejected due to a mutability threshold, a 409 status code will be returned.

        Note: Feedback may be submitted with DSN authentication (see auth documentation).
      operationId: Submit User Feedback
      security:
      - auth_token:
        - project:write
      - dsn: []
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/keys/:
    get:
      description: Return a list of client keys bound to a project.
      operationId: List a Project's Client Keys
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
    post:
      description: Create a new client key bound to a project.  The key's secret and
        public key are generated by the server.
      operationId: Create a New Client Key
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/keys/{key_id}/:
    delete:
      description: Delete a client key.
      operationId: Delete a Client Key
      security:
      - auth_token:
        - project:admin
      tags:
      - Projects
      x-accepts: application/json
    put:
      description: Update a client key.  This can be used to rename a key.
      operationId: Update a Client Key
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/hooks/:
    get:
      description: Return a list of service hooks bound to a project.
      operationId: List a Project's Service Hooks
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
    post:
      description: |-
        Register a new service hook on a project.

        Events include:

        - event.alert: An alert is generated for an event (via rules).
        - event.created: A new event has been processed.

        This endpoint requires the 'servicehooks' feature to be enabled for your project.
      operationId: Register a New Service Hook
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/hooks/{hook_id}/:
    delete:
      description: Remove a service hook.
      operationId: Remove a Service Hook
      security:
      - auth_token:
        - project:admin
      tags:
      - Projects
      x-accepts: application/json
    get:
      description: Return a service hook bound to a project.
      operationId: Retrieve a Service Hook
      security:
      - auth_token:
        - project:read
      tags:
      - Projects
      x-accepts: application/json
    put:
      description: Update a service hook.
      operationId: Update a Service Hook
      security:
      - auth_token:
        - project:write
      tags:
      - Projects
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/events/{event_id}/:
    get:
      description: Return details on an individual event.
      operationId: Retrieve an Event for a Project
      security:
      - auth_token:
        - project:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/events/:
    get:
      description: Return a list of events bound to a project.
      operationId: List a Project's Events
      security:
      - auth_token:
        - project:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/issues/:
    delete:
      description: |-
        Permanently remove the given issues. The list of issues to modify is given through the `id` query parameter.  It is repeated for each issue that should be removed.

        Only queries by 'id' are accepted.

        If any ids are out of scope this operation will succeed without any data mutation.
      operationId: Bulk Remove a List of Issues
      security:
      - auth_token:
        - project:admin
      tags:
      - Events
      x-accepts: application/json
    get:
      description: "Return a list of issues (groups) bound to a project.  All parameters\
        \ are supplied as query string parameters. \n\n A default query of ``is:unresolved``\
        \ is applied. To return results with other statuses send an new query value\
        \ (i.e. ``?query=`` for all results).\n\nThe ``statsPeriod`` parameter can\
        \ be used to select the timeline stats which should be present. Possible values\
        \ are: ``\"\"`` (disable),``\"24h\"``, ``\"14d\"``"
      operationId: List a Project's Issues
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
    put:
      description: |-
        Bulk mutate various attributes on issues.  The list of issues to modify is given through the `id` query parameter.  It is repeated for each issue that should be modified.

        - For non-status updates, the `id` query parameter is required.
        - For status updates, the `id` query parameter may be omitted
        for a batch "update all" query.
        - An optional `status` query parameter may be used to restrict
        mutations to only events with the given status.

        The following attributes can be modified and are supplied as JSON object in the body:

        If any ids are out of scope this operation will succeed without any data mutation.
      operationId: Bulk Mutate a List of Issues
      security:
      - auth_token:
        - project:write
      tags:
      - Events
      x-content-type: application/json
      x-accepts: application/json
  /api/0/issues/{issue_id}/tags/{key}/values/:
    get:
      description: "Returns details for given tag key related to an issue. \n\nWhen\
        \ [paginated](/api/pagination) can return at most 1000 values."
      operationId: List a Tag's Values Related to an Issue
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/issues/{issue_id}/tags/{key}/:
    get:
      description: Returns details for given tag key related to an issue.
      operationId: Retrieve Tag Details
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/issues/{issue_id}/hashes/:
    get:
      description: "This endpoint lists an issue's hashes, which are the generated\
        \ checksums used to aggregate individual events."
      operationId: List an Issue's Hashes
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/issues/{issue_id}/events/oldest/:
    get:
      description: Retrieves the details of the oldest event for an issue.
      operationId: Retrieve the Oldest Event for an Issue
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/issues/{issue_id}/events/latest/:
    get:
      description: Retrieves the details of the latest event for an issue.
      operationId: Retrieve the Latest Event for an Issue
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/issues/{issue_id}/events/:
    get:
      description: This endpoint lists an issue's events.
      operationId: List an Issue's Events
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
  /api/0/issues/{issue_id}/:
    delete:
      description: Removes an individual issue.
      operationId: Remove an Issue
      security:
      - auth_token:
        - event:admin
      tags:
      - Events
      x-accepts: application/json
    get:
      description: "Return details on an individual issue. This returns the basic\
        \ stats for the issue (title, last seen, first seen), some overall numbers\
        \ (number of comments, user reports) as well as the summarized event data."
      operationId: Retrieve an Issue
      security:
      - auth_token:
        - event:read
      tags:
      - Events
      x-accepts: application/json
    put:
      description: Updates an individual issue's attributes.  Only the attributes
        submitted are modified.
      operationId: Update an Issue
      security:
      - auth_token:
        - event:write
      tags:
      - Events
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/:
    get:
      description: Return a list of releases for a given organization.
      operationId: List an Organization's Releases
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    post:
      description: |-
        Create a new release for the given organization.  Releases are used by
        Sentry to improve its error reporting abilities by correlating
        first seen events with the release that might have introduced the
        problem.
        Releases are also necessary for source maps and other debug features
        that require manual upload for functioning well.
      operationId: Create a New Release for an Organization
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/{version}/:
    delete:
      description: Delete a release for a given organization.
      operationId: Delete an Organization's Release
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    get:
      description: Return a release for a given organization.
      operationId: Retrieve an Organization's Releases
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    put:
      description: Update a release for a given organization.
      operationId: Update an Organization's Release
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/{version}/files/:
    get:
      description: Return a list of files for a given release.
      operationId: List an Organization's Release Files
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    post:
      description: Upload a new organization release file.
      operationId: Upload a New Organization Release File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: multipart/form-data
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/:
    get:
      description: Return a list of files for a given release.
      operationId: List a Project's Release Files
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    post:
      description: Upload a new project release file.
      operationId: Upload a New Project Release File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: multipart/form-data
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/{version}/files/{file_id}/:
    delete:
      description: Delete a file for a given release.
      operationId: Delete an Organization Release's File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    get:
      description: Retrieve a file for a given release.
      operationId: Retrieve an Organization Release's File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    put:
      description: Update an organization release file.
      operationId: Update an Organization Release File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: application/json
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/{file_id}/:
    delete:
      description: Delete a file for a given release.
      operationId: Delete a Project Release's File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    get:
      description: Retrieve a file for a given release.
      operationId: Retrieve a Project Release's File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    put:
      description: Update a project release file.
      operationId: Update a Project Release File
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/{version}/commits/:
    get:
      description: List an organization release's commits.
      operationId: List an Organization Release's Commits
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/releases/{version}/commits/:
    get:
      description: List a project release's commits.
      operationId: List a Project Release's Commits
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/{version}/commitfiles/:
    get:
      description: Retrieve files changed in a release's commits
      operationId: Retrieve Files Changed in a Release's Commits
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
  /api/0/projects/{organization_slug}/{project_slug}/releases/{version}/resolved/:
    get:
      description: List issues to be resolved in a particular release.
      operationId: List Issues to be Resolved in a Particular Release
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/releases/{version}/deploys/:
    get:
      description: Return a list of deploys for a given release.
      operationId: List a Release's Deploys
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-accepts: application/json
    post:
      description: Create a deploy.
      operationId: Create a New Deploy for an Organization
      security:
      - auth_token:
        - project:releases
      tags:
      - Releases
      x-content-type: application/json
      x-accepts: application/json
  /api/0/organizations/{organization_slug}/sentry-app-installations/:
    get:
      description: Return a list of integration platform installations for a given
        organization.
      operationId: List an Organization's Integration Platform Installations
      security:
      - auth_token:
        - org:read
        - org:integrations
      tags:
      - Integration
      x-accepts: application/json
  /api/0/sentry-app-installations/{uuid}/external-issues/:
    post:
      description: Create an external issue from an integration platform integration.
      operationId: Create an External Issue
      security:
      - auth_token:
        - event:write
      tags:
      - Integration
      x-content-type: application/json
      x-accepts: application/json
  /api/0/sentry-app-installations/{uuid}/external-issues/{external_issue_id}/:
    delete:
      description: Delete an external issue.
      operationId: Delete an External Issue
      security:
      - auth_token:
        - event:admin
      tags:
      - Integration
      x-accepts: application/json
components:
  securitySchemes:
    auth_token:
      scheme: bearer
      type: http
    dsn:
      scheme: DSN
      type: http

